[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.16", features = ["json"] }

serde = { version = "1.0.107", features = ["derive"] }
serde_json = "1.0.91"

tokio = "1.27.0"

clap = {version = "4.1.11", features = ["derive", "env"] }

image = "0.24.5"

md5 = "0.7.0"

control_panel = { path = "../control_panel" }
worker = { path = "../worker" }